In [1]:
# convert list into numpy array

import numpy as np

my_list = [1,5,8,9,7,5]

my_array = np.array(my_list)

print(my_array)



[1 5 8 9 7 5]


In [2]:
# create 3*3 matrix with value range 2 to 10

matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
# to append value at the end of array

 
a_array = np.array([[4, 5, 6],[1,2,3]])

values= np.random.randint(5,10,(2,3))

b_array = np.append(a_array,values) # or (a_array,values,axis=0) 

c_array=b_array.reshape(4,3)

print(c_array)


[[4 5 6]
 [1 2 3]
 [7 9 9]
 [7 9 6]]


In [4]:
# Reshape the array 
a_array =np.array([[1,2,3],[2,5,6]])

b_array=a_array.reshape(3,2)
print(b_array)

[[1 2]
 [3 2]
 [5 6]]
