In [1]:
#  (4.1) to add, subtract, multiply, divide arguments element-wise 

# KISHAN JUNGI
# 216270307014

import numpy as np

a_array=np.array([1,2,3])
b_array=np.array([1,2,3])

print("Addition of numpy arrays")
add=a_array+b_array
print(add)
print()

print("Subtraction of numpy arrays")
sub= a_array-b_array
print(sub)
print()

print("Multiplication of numpy arrays")
mup = a_array*b_array
print(mup)
print()

print("Division of numpy arrays")
div= a_array/b_array
print(div)
print()

print("Subtraction of numpy arrays")
sub= a_array-b_array
print(sub)
print()




Addition of numpy arrays
[2 4 6]

Subtraction of numpy arrays
[0 0 0]

Multiplication of numpy arrays
[1 4 9]

Division of numpy arrays
[1. 1. 1.]

Subtraction of numpy arrays
[0 0 0]



In [2]:
# (4.2) to round elements of the array to the nearest integer

# KISHAN JUNGI
# 216270307014

a1=np.array([1.2,2.5,5.6,4.2,3.7,5.4])

round_array=np.round(a1)

print("Round of Array")
print(round_array)
print()


Round of Array
[1. 2. 6. 4. 4. 5.]



In [3]:
# (4.3) to calculate mean across dimension, in a 2D numpy array

# KISHAN JUNGI
# 216270307014

arr = np.array([[5, 8, 3, 7], [9, 4, 2, 6]])
arr1 = np.mean(arr) 
print("Round of 2-D Array")
print(arr1)


Round of 2-D Array
5.5


In [4]:
# (4.4) to calculate the difference between neighboring elements, elementwise of a given array


# KISHAN JUNGI
# 216270307014

input_array = np.array([1, 4, 7, 2, 9])

print("differences between neighboring elements")
differences = np.diff(input_array)

print(differences)


differences between neighboring elements
[ 3  3 -5  7]
